name       : perl-pod-usage
version    : '1.70'
release    : 5
source     :
    - https://cpan.metacpan.org/authors/id/M/MA/MAREKR/Pod-Usage-1.70.tar.gz : 54fc12b61c7661e12e102e56d68f18dfbe8899482bb8f9925db2a18b8b64d43a
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Pod::Usage - print a usage message from embedded pod documentation
description: |
    Pod::Usage - print a usage message from embedded pod documentation
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
